/**
 * Simple JSON defining Digivolution.
 * Each Digimon knows only its direct evolutions.
 */
const DIGIMONS = {
  greymon: { name:"Greymon", stage:"Champion", evolvesTo:[], method:"—" },
  tyrannomon: { name:"Tyrannomon", stage:"Champion", evolvesTo:[], method:"Heavy weight" },
  garurumon: { name:"Garurumon", stage:"Champion", evolvesTo:[], method:"High speed" },
  botamon: { name:"Botamon", stage:"Baby", evolvesTo:["koromon"], method:"Time" },
  punimon: { name:"Punimon", stage:"Baby", evolvesTo:["tsunomon"], method:"Time" },
  poyomon: { name:"Poyomon", stage:"Baby", evolvesTo:["tokomon"], method:"Time" },
  conomon: { name:"Conomon", stage:"Baby", evolvesTo:["kokomon"], method:"Time" },
  yukimiBotamon: { name:"YukimiBotamon", stage:"Baby", evolvesTo:["nyaromon"], method:"Time" },
  pabumon: { name:"Pabumon", stage:"Baby", evolvesTo:["motimon"], method:"Time" },
  jyarimon: { name:"Jyarimon", stage:"Baby", evolvesTo:["gigimon"], method:"Time" },
  zerimon: { name:"Zerimon", stage:"Baby", evolvesTo:["gummymon"], method:"Time" },
  kuramon: { name:"Kuramon", stage:"Baby", evolvesTo:["tsunamon"], method:"Time" },
  pichimon: { name:"Pichimon", stage:"Baby", evolvesTo:["bukamon"], method:"Time" },
  yuramon: { name:"Yuramon", stage:"Baby", evolvesTo:["tanemon"], method:"Time" },
  koromon: { name:"Koromon", stage:"In-Training", evolvesTo:["agumon","toyAgumon", "agumonBlack", "veemon", "shoutmon"], method:"HP + Discipline" },
  tsunomon: { name:"Tsunomon", stage:"In-Training", evolvesTo:["gabumon","gaomon", "psychemon", "gabumonBlack", "gumdramon"], method:"HP + Discipline" },
  tokomon: { name:"Tokomon", stage:"In-Training", evolvesTo:["patamon","biyomon", "tsukaimon", "hackmon", "lucemon"], method:"HP + Discipline" },
  motimon: { name:"Motimon", stage:"In-Training", evolvesTo:["tentomon","wormmon", "gotsumon", "hackmon", "hagurumon"], method:"HP + Discipline" },
  tanemon: { name:"Tanemon", stage:"In-Training", evolvesTo:["palmon","renamon", "aruraumon", "goblimon", "demiDevimon"], method:"HP + Discipline" },
  gigimon: { name:"Gigimon", stage:"In-Training", evolvesTo:["guilmon","goblimon", "solarmon", "gotsumon", "shoutmon"], method:"HP + Discipline" },
  gummymon: { name:"Gummymon", stage:"In-Training", evolvesTo:["terriermon","toyAgumon", "clearAgumon", "hagurumon", "gaomon"], method:"HP + Discipline" },
  kokomon: { name:"Kokomon", stage:"In-Training", evolvesTo:["lopmon","demiDevimon", "shamamon", "toyAgumonBlack", "wormmon"], method:"HP + Discipline" },
  tsunemon: { name:"Tsunemon", stage:"In-Training", evolvesTo:["keramon", "toyAgumonBlack", "agumonBlack", "gabumonBlack", "tsukaimon"], method:"Time" },
  nyaromon: { name:"Nyaromon", stage:"In-Training", evolvesTo:["salamon","snowAgumon", "renamon", "biyomon", "lucemon"], method:"HP + Discipline" },
  bukamon: { name:"Bukamon", stage:"In-Training", evolvesTo:["gomamon","veemon", "snowGoblimon", "clearAgumon", "gumdramon"], method:"HP + Discipline" },
  agumon: { name:"Agumon", stage:"Rookie", evolvesTo:["greymon","tyrannomon", "meramon", "greymonBlue"], method:"High ATK" },
  gabumon: { name:"Gabumon", stage:"Rookie", evolvesTo:["garurumon", "gaoGamon", "garurumonBlack", "seadramon"], method:"Speed + Bond" },
  biyomon: { name:"Biyomon", stage:"Rookie", evolvesTo:["birdramon", "piddomon", "redVeedreamon", "youjomon"], method:"Speed + Bond" },
  patamon: { name:"Patamon", stage:"Rookie", evolvesTo:["angemon", "piddomon", "veedreamon", "growlmonOrange"], method:"Speed + Bond" },
  tentomon: { name:"Tentomon", stage:"Rookie", evolvesTo:["kabuterimon", "redVegiemon", "woodmon", "bomberNanimon"], method:"Speed + Bond" },
  gomamon: { name:"Gomamon", stage:"Rookie", evolvesTo:["ikkakumon", "seadreamon", "icemon", "sorcermon"], method:"Speed + Bond" },
  palmon: { name:"Palmon", stage:"Rookie", evolvesTo:["togemon", "woodmon", "vegiemon", "redVegiemon"], method:"Speed + Bond" },
  salamon: { name:"Salamon", stage:"Rookie", evolvesTo:["gatomon", "blackGatomon", "gargomon", "meicoomon"], method:"Speed + Bond" },
  veemon: { name:"Veemon", stage:"Rookie", evolvesTo:["exVeemon", "veedreamon", "meramon", "goldVeedramon"], method:"Speed + Bond" },
  wormmon: { name:"Gabumon", stage:"Rookie", evolvesTo:["stingmon", "kuwagamon", "kabuterimon", "devimon"], method:"Speed + Bond" },
  guilmon: { name:"Guilmon", stage:"Rookie", evolvesTo:["growlmon", "growlmonOrange", "tyrannomon", "redVeedramon"], method:"Speed + Bond" },
  terriermon: { name:"Terriermon", stage:"Rookie", evolvesTo:["gargomon", "ikkakumon", "angemon", "ogremon"], method:"Speed + Bond" },
  lopmon: { name:"Lopmon", stage:"Rookie", evolvesTo:["turuiemon", "kyubimonSilver", "wizardmon", "blackGatomon"], method:"Speed + Bond" },
  renamon: { name:"Renamon", stage:"Rookie", evolvesTo:["kyubimon", "kyubimonSilver", "turuiemon", "leomon"], method:"Speed + Bond" },
  gaomon: { name:"Gaomon", stage:"Rookie", evolvesTo:["gaoGamon", "garurumon", "leomon", "togemon"], method:"Speed + Bond" },
  hagurumon: { name:"Hagurumon", stage:"Rookie", evolvesTo:["guardomon", "goldVeedramon", "kuwagamon", "bomberNanimon"], method:"Speed + Bond" },
  gotsumon: { name:"Gotsumon", stage:"Rookie", evolvesTo:["icemon", "ogremon", "tyrannomon", "nanimon"], method:"Speed + Bond" },
  goblimon: { name:"Goblimon", stage:"Rookie", evolvesTo:["ogremon", "nanimon", "woodmon", "gaoGamon"], method:"Speed + Bond" },
  toyAgumon: { name:"ToyAgumon", stage:"Rookie", evolvesTo:["wizardmon", "greymon", "guardromonGold", "growlmonOrange"], method:"Speed + Bond" },
  demiDevimon: { name:"DemiDevimon", stage:"Rookie", evolvesTo:["devimon", "blackGatomon", "iceDevimon", "chrysalimon"], method:"Speed + Bond" },
  hackmon: { name:"Hackmon", stage:"Rookie", evolvesTo:["leomon", "gururumon", "exVeemon", "goldVeedramon"], method:"Speed + Bond" },
  agumonBlack: { name:"Agumon (Black)", stage:"Rookie", evolvesTo:["greymonBlue", "growlmon", "saberdramon", "fugamon"], method:"Speed + Bond" },
  snowagumon: { name:"SnowAgumon", stage:"Rookie", evolvesTo:["sorcermon", "gatomon", "hyogamon", "icemon"], method:"Speed + Bond" },
  gabumonBlack: { name:"Gabumon (Black)", stage:"Rookie", evolvesTo:["garurumonBlack", "stringmon", "gururumon", "saberdramon"], method:"Speed + Bond" },
  psychemon: { name:"Psychemon", stage:"Rookie", evolvesTo:["gururumon", "kyubimon", "bomberNanimon", "gargomon"], method:"Speed + Bond" },
  tsukaimon: { name:"Tsukaimon", stage:"Rookie", evolvesTo:["saberdreamon", "devimon", "youkomon", "garurumonBlack"], method:"Speed + Bond" },
  aruraumon: { name:"Aruraumon", stage:"Rookie", evolvesTo:["vegiemon", "youkomon", "togemon", "stingmon"], method:"Speed + Bond" },
  toyAgumonBlack: { name:"ToyAgumon (Black)", stage:"Rookie", evolvesTo:["nanimon", "guardomon", "fugamon", "greymonBlue"], method:"Speed + Bond" },
  clearAgumon: { name:"ClearAgumon", stage:"Rookie", evolvesTo:["guardomonGold", "iceDevimon", "exVeemon", "hyogamon"], method:"Speed + Bond" },
  solarmon: { name:"Solarmon", stage:"Rookie", evolvesTo:["meramon", "redVegiemon", "birdramon", "guardomonGold"], method:"Speed + Bond" },
  snowGoblimon: { name:"SnowGoblimon", stage:"Rookie", evolvesTo:["hyogamon", "ikkakumon", "seadreamon", "kyubimonSilver"], method:"Speed + Bond" },
  shamamon: { name:"Shamamon", stage:"Rookie", evolvesTo:["fugamon", "vegiemon", "kuwagamon", "sorcermon"], method:"Speed + Bond" },
  keramon: { name:"Keramon", stage:"Rookie", evolvesTo:["chrysalimon", "guardomon", "meicoomon", "kabuterimon"], method:"Speed + Bond" },
  gumdreamon: { name:"Gumdramon", stage:"Rookie", evolvesTo:["arresterdramon", "veedreamon", "turuiemon", "gatomon"], method:"Speed + Bond" },
  shoutmon: { name:"Shoutmon", stage:"Rookie", evolvesTo:["omniShoutmon", "growlmon", "greymon", "redVeedreamon"], method:"Speed + Bond" }
};
