/**
 * Simple JSON defining Digivolution.
 * Each Digimon knows only its direct evolutions.
 * Icons: https://www.hiclipart.com/free-transparent-background-png-clipart-viify
 */
const DIGIMONS = {
  botamon: { name: "Botamon", stage: "Baby", evolvesTo: ["koromon"], method: "-" , icon: "./assets/botamon.png" },
  punimon: { name: "Punimon", stage: "Baby", evolvesTo: ["tsunomon"], method: "-", icon:'./assets/punimon.png' },
  poyomon: { name: "Poyomon", stage: "Baby", evolvesTo: ["tokomon"], method: "-" , icon: "./assets/poyomon.png" },
  conomon: { name: "Conomon", stage: "Baby", evolvesTo: ["kokomon"], method: "-" , icon: "./assets/conomon.png" },
  yukimiBotamon: { name: "YukimiBotamon", stage: "Baby", evolvesTo: ["nyaromon"], method: "-" , icon: "./assets/yukimibotamon.png" },
  pabumon: { name: "Pabumon", stage: "Baby", evolvesTo: ["motimon"], method: "-" , icon: "./assets/pabumon.png" },
  jyarimon: { name: "Jyarimon", stage: "Baby", evolvesTo: ["gigimon"], method: "-" , icon: "./assets/jyarimon.png" },
  zerimon: { name: "Zerimon", stage: "Baby", evolvesTo: ["gummymon"], method: "-" , icon: "./assets/zerimon.png" },
  kuramon: { name: "Kuramon", stage: "Baby", evolvesTo: ["tsumemon"], method: "-" , icon: "./assets/kuramon.png" },
  pichimon: { name: "Pichimon", stage: "Baby", evolvesTo: ["bukamon"], method: "-" , icon: "./assets/pichimon.png" },
  yuramon: { name: "Yuramon", stage: "Baby", evolvesTo: ["tanemon"], method: "-" , icon: "./assets/yuramon.png" },
  koromon: { name: "Koromon", stage: "In-Training", evolvesTo: ["agumon", "toyAgumon", "agumonBlack", "veemon", "shoutmon"], method: ["Time"] , icon: "./assets/koromon.png" },
  tsunomon: { name: "Tsunomon", stage: "In-Training", evolvesTo: ["gabumon", "gaomon", "psychemon", "gabumonBlack", "gumdramon"], method: ["Time"] , icon: "./assets/tsunomon.png" },
  tokomon: { name: "Tokomon", stage: "In-Training", evolvesTo: ["patamon", "biyomon", "tsukaimon", "hackmon", "lucemon"], method: ["Time"] , icon: "./assets/tokomon.png" },
  motimon: { name: "Motimon", stage: "In-Training", evolvesTo: ["tentomon", "wormmon", "gotsumon", "hackmon", "hagurumon"], method: ["Time"] , icon: "./assets/motimon.png" },
  tanemon: { name: "Tanemon", stage: "In-Training", evolvesTo: ["palmon", "renamon", "aruraumon", "goblimon", "demiDevimon"], method: ["Time"] , icon: "./assets/tanemon.png" },
  gigimon: { name: "Gigimon", stage: "In-Training", evolvesTo: ["guilmon", "goblimon", "solarmon", "gotsumon", "shoutmon"], method: ["Time"] , icon: "./assets/gigimon.png" },
  gummymon: { name: "Gummymon", stage: "In-Training", evolvesTo: ["terriermon", "toyAgumon", "clearAgumon", "hagurumon", "gaomon"], method: ["Time"] , icon: "./assets/gummymon.png" },
  kokomon: { name: "Kokomon", stage: "In-Training", evolvesTo: ["lopmon", "demiDevimon", "shamamon", "toyAgumonBlack", "wormmon"], method: ["Time"] , icon: "./assets/kokomon.png" },
  tsumemon: { name: "Tsumemon", stage: "In-Training", evolvesTo: ["keramon", "toyAgumonBlack", "agumonBlack", "gabumonBlack", "tsukaimon"], method: ["Time"] , icon: "./assets/tsumemon.png" },
  nyaromon: { name: "Nyaromon", stage: "In-Training", evolvesTo: ["salamon", "snowAgumon", "renamon", "biyomon", "lucemon"], method: ["Time"] , icon: "./assets/nyaromon.png" },
  bukamon: { name: "Bukamon", stage: "In-Training", evolvesTo: ["gomamon", "veemon", "snowGoblimon", "clearAgumon", "gumdramon"], method: ["Time"] , icon: "./assets/bukamon.png" },
  agumon: { name: "Agumon", stage: "Rookie", evolvesTo: ["greymon", "tyrannomon", "meramon", "greymonBlue", "numemon", "geremon"], method: ["HP >= 1900", "STR >= 890", "KEY PTS = 2"], icon: "./assets/agumon.png" },
  gabumon: { name: "Gabumon", stage: "Rookie", evolvesTo: ["garurumon", "gaoGamon", "garurumonBlack", "seadramon", "numemon", "geremon"], method: "-" , icon: "./assets/gabumon.png" },
  biyomon: { name: "Biyomon", stage: "Rookie", evolvesTo: ["birdramon", "piddomon", "redVeedramon", "youkomon", "numemon", "geremon"], method: "-" , icon: "./assets/biyomon.png" },
  patamon: { name: "Patamon", stage: "Rookie", evolvesTo: ["angemon", "piddomon", "veedramon", "growlmonOrange", "numemon", "geremon"], method: "-" , icon: "./assets/patamon.png" },
  tentomon: { name: "Tentomon", stage: "Rookie", evolvesTo: ["kabuterimon", "redVegiemon", "woodmon", "bomberNanimon", "numemon", "geremon"], method: "-" , icon: "./assets/tentomon.png" },
  gomamon: { name: "Gomamon", stage: "Rookie", evolvesTo: ["ikkakumon", "seadramon", "icemon", "sorcermon", "numemon", "geremon"], method: ["STR >= 50", "STA >= 130", "KEY PTS = 2"] , icon: "./assets/gomamon.png" },
  palmon: { name: "Palmon", stage: "Rookie", evolvesTo: ["togemon", "woodmon", "vegiemon", "redVegiemon", "numemon", "geremon"], method: "-" , icon: "./assets/palmon.png" },
  salamon: { name: "Salamon", stage: "Rookie", evolvesTo: ["gatomon", "blackGatomon", "gargomon", "meicoomon", "numemon", "geremon"], method: "-" , icon: "./assets/salamon.png" },
  veemon: { name: "Veemon", stage: "Rookie", evolvesTo: ["exVeemon", "veedramon", "meramon", "goldVeedramon", "numemon", "geremon"], method: "-" , icon: "./assets/veemon.png" },
  wormmon: { name: "Wormmon", stage: "Rookie", evolvesTo: ["stingmon", "kuwagamon", "kabuterimon", "devimon", "numemon", "geremon"], method: "-" , icon: "./assets/wormmon.png" },
  guilmon: { name: "Guilmon", stage: "Rookie", evolvesTo: ["growlmon", "growlmonOrange", "tyrannomon", "redVeedramon", "numemon", "geremon"], method: "-" , icon: "./assets/guilmon.png" },
  terriermon: { name: "Terriermon", stage: "Rookie", evolvesTo: ["gargomon", "ikkakumon", "angemon", "ogremon", "numemon", "geremon"], method: "-" , icon: "./assets/terriermon.png" },
  lopmon: { name: "Lopmon", stage: "Rookie", evolvesTo: ["turuiemon", "kyubimonSilver", "wizardmon", "blackGatomon", "numemon", "geremon"], method: "-" , icon: "./assets/lopmon.png" },
  renamon: { name: "Renamon", stage: "Rookie", evolvesTo: ["kyubimon", "kyubimonSilver", "turuiemon", "leomon", "numemon", "geremon"], method: "-" , icon: "./assets/renamon.png" },
  gaomon: { name: "Gaomon", stage: "Rookie", evolvesTo: ["gaoGamon", "garurumon", "leomon", "togemon", "numemon", "geremon"], method: "-" , icon: "./assets/gaomon.png" },
  hagurumon: { name: "Hagurumon", stage: "Rookie", evolvesTo: ["guardomon", "goldVeedramon", "kuwagamon", "bomberNanimon", "numemon", "geremon"], method: "-" , icon: "./assets/hagurumon.png" },
  gotsumon: { name: "Gotsumon", stage: "Rookie", evolvesTo: ["icemon", "ogremon", "tyrannomon", "nanimon", "numemon", "geremon"], method: "-" , icon: "./assets/gotsumon.png" },
  goblimon: { name: "Goblimon", stage: "Rookie", evolvesTo: ["ogremon", "nanimon", "woodmon", "gaoGamon", "numemon", "geremon"], method: "-" , icon: "./assets/goblimon.png" },
  toyAgumon: { name: "ToyAgumon", stage: "Rookie", evolvesTo: ["wizardmon", "greymon", "guardomonGold", "growlmonOrange", "numemon", "geremon"], method: "-" , icon: "./assets/toyagumon.png" },
  demiDevimon: { name: "DemiDevimon", stage: "Rookie", evolvesTo: ["devimon", "blackGatomon", "iceDevimon", "chrysalimon", "numemon", "geremon"], method: "-" , icon: "./assets/demidevimon.png" },
  lucemon: { name: "Lucemon", stage: "Rookie", evolvesTo: ["iceDevimon", "piddomon", "wizardmon", "chrysalimon", "numemon", "geremon"], method: "-" , icon: "./assets/lucemon.png" },
  hackmon: { name: "Hackmon", stage: "Rookie", evolvesTo: ["leomon", "gururumon", "exVeemon", "goldVeedramon", "numemon", "geremon"], method: "-" , icon: "./assets/hackmon.png" },
  agumonBlack: { name: "Agumon (Black)", stage: "Rookie", evolvesTo: ["greymonBlue", "growlmon", "saberdramon", "numemon", "fugamon"], method: "-" , icon: "./assets/agumonblack.png" },
  snowAgumon: { name: "SnowAgumon", stage: "Rookie", evolvesTo: ["sorcermon", "gatomon", "hyogamon", "icemon", "numemon", "geremon"], method: "-" , icon: "./assets/snowagumon.png" },
  gabumonBlack: { name: "Gabumon (Black)", stage: "Rookie", evolvesTo: ["garurumonBlack", "stingmon", "gururumon", "saberdramon", "numemon", "geremon"], method: "-" , icon: "./assets/gabumonblack.png" },
  psychemon: { name: "Psychemon", stage: "Rookie", evolvesTo: ["gururumon", "kyubimon", "bomberNanimon", "gargomon", "numemon", "geremon"], method: "-" , icon: "./assets/psychemon.png" },
  tsukaimon: { name: "Tsukaimon", stage: "Rookie", evolvesTo: ["saberdramon", "devimon", "youkomon", "garurumonBlack", "numemon", "geremon"], method: "-" , icon: "./assets/tsukaimon.png" },
  aruraumon: { name: "Aruraumon", stage: "Rookie", evolvesTo: ["vegiemon", "youkomon", "togemon", "stingmon", "numemon", "geremon"], method: "-" , icon: "./assets/aruraumon.png" },
  toyAgumonBlack: { name: "ToyAgumon (Black)", stage: "Rookie", evolvesTo: ["nanimon", "guardomon", "fugamon", "greymonBlue", "numemon", "geremon"], method: "-" , icon: "./assets/toyagumonblack.png" },
  clearAgumon: { name: "ClearAgumon", stage: "Rookie", evolvesTo: ["guardomonGold", "iceDevimon", "exVeemon", "hyogamon", "numemon", "geremon"], method: "-" , icon: "./assets/clearagumon.png" },
  solarmon: { name: "Solarmon", stage: "Rookie", evolvesTo: ["meramon", "redVegiemon", "birdramon", "guardomonGold", "numemon", "geremon"], method: "-" , icon: "./assets/solarmon.png" },
  snowGoblimon: { name: "SnowGoblimon", stage: "Rookie", evolvesTo: ["hyogamon", "ikkakumon", "seadramon", "kyubimonSilver", "numemon", "geremon"], method: "-" , icon: "./assets/snowgoblimon.png" },
  shamamon: { name: "Shamamon", stage: "Rookie", evolvesTo: ["fugamon", "vegiemon", "kuwagamon", "sorcermon", "numemon", "geremon"], method: "-" , icon: "./assets/shamamon.png" },
  keramon: { name: "Keramon", stage: "Rookie", evolvesTo: ["chrysalimon", "guardomon", "meicoomon", "kabuterimon", "numemon", "geremon"], method: "-" , icon: "./assets/keramon.png" },
  gumdramon: { name: "Gumdramon", stage: "Rookie", evolvesTo: ["arresterdramon", "veedramon", "turuiemon", "gatomon", "numemon", "geremon"], method: "-" , icon: "./assets/gumdramon.png" },
  shoutmon: { name: "Shoutmon", stage: "Rookie", evolvesTo: ["omniShoutmon", "growlmon", "greymon", "redVeedramon", "numemon", "geremon"], method: "-" , icon: "./assets/shoutmon.png" },
  greymon: { name: "Greymon", stage: "Champion", evolvesTo: ["metalGreymon", "metalGreymonBlue", "warGrowlmonOrange"], method: "-" , icon: "./assets/greymon.png" },
  garurumon: { name: "Garurumon", stage: "Champion", evolvesTo: ["wereGarurumon", "grapLeomon", "machGaogamon"], method: "-" , icon: "./assets/garurumon.png" },
  birdramon: { name: "Birdramon", stage: "Champion", evolvesTo: ["garudamon", "aeroVeedramon", "agunimon"], method: "-" , icon: "./assets/birdramon.png" },
  angemon: { name: "Angemon", stage: "Champion", evolvesTo: ["magnaAngemon", "blueMeramon", "taomon"], method: "-" , icon: "./assets/angemon.png" },
  kabuterimon: { name: "Kabuterimon", stage: "Champion", evolvesTo: ["megaKabuterimon", "megaKabuterimonBlue", "skullGreymon"], method: "-" , icon: "./assets/kabuterimon.png" },
  ikkakumon: { name: "Ikkakumon", stage: "Champion", evolvesTo: ["zudomon", "iceLeomon", "rapidmon"], method: "-" , icon: "./assets/ikkakumon.png" },
  togemon: { name: "Togemon", stage: "Champion", evolvesTo: ["lillymon", "mamemon", "ladyDevimon"], method: "-" , icon: "./assets/togemon.png" },
  gatomon: { name: "Gatomon", stage: "Champion", evolvesTo: ["angewomon", "taomonSilver", "lillymon"], method: "-" , icon: "./assets/gatomon.png" },
  exVeemon: { name: "ExVeemon", stage: "Champion", evolvesTo: ["aeroVeedramon", "metalTyrannomon", "garudamon", "paildramon"], method: "-" , icon: "./assets/exveemon.png" },
  stingmon: { name: "Stingmon", stage: "Champion", evolvesTo: ["megaKabuterimonBlue", "okuwamon", "megaKabuterimon", "paildramon"], method: "-" , icon: "./assets/stingmon.png" },
  growlmon: { name: "Growlmon", stage: "Champion", evolvesTo: ["warGrowlmon", "skullGreymon", "blackWarGrowlmon"], method: "-" , icon: "./assets/growlmon.png" },
  gargomon: { name: "Gargomon", stage: "Champion", evolvesTo: ["rapidmon", "metalMamemon", "rapidmonGold"], method: "-" , icon: "./assets/gargomon.png" },
  turuiemon: { name: "Turuiemon", stage: "Champion", evolvesTo: ["antylamon", "megadramon", "monzaemon"], method: "-" , icon: "./assets/turuiemon.png" },
  kyubimon: { name: "Kyubimon", stage: "Champion", evolvesTo: ["taomon", "monzaemon", "wereGarurumon"], method: "-" , icon: "./assets/kyubimon.png" },
  gaoGamon: { name: "GaoGamon", stage: "Champion", evolvesTo: ["machGaogamon", "wereGarurumon", "grapLeomon"], method: "-" , icon: "./assets/gaogamon.png" },
  wizardmon: { name: "Wizardmon", stage: "Champion", evolvesTo: ["lucemonFm", "myotismon", "magnaAngemon"], method: "-" , icon: "./assets/wizardmon.png" },
  devimon: { name: "Devimon", stage: "Champion", evolvesTo: ["myotismon", "doumon", "infermon"], method: "-" , icon: "./assets/devimon.png" },
  veedramon: { name: "Veedramon", stage: "Champion", evolvesTo: ["aeroVeedramon", "machGaogamon", "megaSeadramon"], method: "-" , icon: "./assets/veedramon.png" },
  tyrannomon: { name: "Tyrannomon", stage: "Champion", evolvesTo: ["metalTyrannomon", "metalGreymonBlue", "warGrowlmon"], method: "-" , icon: "./assets/tyrannomon.png" },
  ogremon: { name: "Ogremon", stage: "Champion", evolvesTo: ["skullGreymon", "waruSeadramon", "metalTyrannomon"], method: "-" , icon: "./assets/ogremon.png" },
  leomon: { name: "Leomon", stage: "Champion", evolvesTo: ["grapLeomon", "rapidmon", "iceLeomon"], method: "-" , icon: "./assets/leomon.png" },
  meramon: { name: "Meramon", stage: "Champion", evolvesTo: ["blueMeramon", "garudamon", "myotismon"], method: "-" , icon: "./assets/meramon.png" },
  vegiemon: { name: "Vegiemon", stage: "Champion", evolvesTo: ["mamemon", "etemon", "okuwamon"], method: "-" , icon: "./assets/vegiemon.png" },
  nanimon: { name: "Nanimon", stage: "Champion", evolvesTo: ["waruSeadramon", "doumon", "etemon"], method: "-" , icon: "./assets/nanimon.png" },
  seadramon: { name: "Seadramon", stage: "Champion", evolvesTo: ["megaSeadramon", "gigadramon", "waruSeadramon"], method: ["HP >= 1000", "MP >= 700", "SPD >= 250", "WEOGHT >= 20", "TF <= 5", "VICTORIES >= 15", "KEY PTS = 4"] , icon: "./assets/seadramon.png" },
  kuwagamon: { name: "Kuwagamon", stage: "Champion", evolvesTo: ["okuwamon", "warGrowlmonOrange", "infermon"], method: "-" , icon: "./assets/kuwagamon.png" },
  guardomon: { name: "Guardomon", stage: "Champion", evolvesTo: ["datamon", "metalMamemon", "metalTyrannomon"], method: "-" , icon: "./assets/guardomon.png" },
  woodmon: { name: "Woodmon", stage: "Champion", evolvesTo: ["okuwamon", "taomon", "mamemon"], method: "-" , icon: "./assets/woodmon.png" },
  bomberNanimon: { name: "BomberNanimon", stage: "Champion", evolvesTo: ["megadramon", "meteormon", "metalMamemon"], method: "-" , icon: "./assets/bombernanimon.png" },
  icemon: { name: "Icemon", stage: "Champion", evolvesTo: ["meteormon", "mamemon", "zudomon"], method: "-" , icon: "./assets/icemon.png" },
  hyogamon: { name: "Hyogamon", stage: "Champion", evolvesTo: ["blueMeramon", "zudomon", "iceLeomon"], method: "-" , icon: "./assets/hyogamon.png" },
  piddomon: { name: "Piddomon", stage: "Champion", evolvesTo: ["meteormon", "angewomon", "monzaemon"], method: "-" , icon: "./assets/piddomon.png" },
  kyubimonSilver: { name: "Kyubimon (Silver)", stage: "Champion", evolvesTo: ["taomonSilver", "gigadramon", "antylamon"], method: "-" , icon: "./assets/kyubimonsilver.png" },
  gururumon: { name: "Gururumon", stage: "Champion", evolvesTo: ["blackWarGrowlmon", "wereGarurumonBlack", "taomonSilver"], method: "-" , icon: "./assets/gururumon.png" },
  saberdramon: { name: "Saberdramon", stage: "Champion", evolvesTo: ["megadramon", "waruSeadramon", "ladyDevimon"], method: "-" , icon: "./assets/saberdramon.png" },
  blackGatomon: { name: "BlackGatomon", stage: "Champion", evolvesTo: ["ladyDevimon", "antylamon", "maycrackmonVm"], method: "-" , icon: "./assets/blackgatomon.png" },
  fugamon: { name: "Fugamon", stage: "Champion", evolvesTo: ["blackWarGrowlmon", "garudamon", "machGaogamon"], method: "-" , icon: "./assets/fugamon.png" },
  guardomonGold: { name: "Guardomon (Gold)", stage: "Champion", evolvesTo: ["metalMamemon", "datamon", "rapidmonGold"], method: "-" , icon: "./assets/guardomongold.png" },
  youkomon: { name: "Youkomon", stage: "Champion", evolvesTo: ["doumon", "megaKabuterimonBlue", "wereGarurumonBlack"], method: "-" , icon: "./assets/youkomon.png" },
  redVeedramon: { name: "RedVeedramon", stage: "Champion", evolvesTo: ["warGrowlmon", "megaKabuterimon", "agunimon"], method: "-" , icon: "./assets/redveedramon.png" },
  goldVeedramon: { name: "GoldVeedramon", stage: "Champion", evolvesTo: ["megaSeadramon", "metalGreymon", "rapidmonGold"], method: "-" , icon: "./assets/goldveedramon.png" },
  growlmonOrange: { name: "Growlmon (Orange)", stage: "Champion", evolvesTo: ["warGrowlmonOrange", "metalGreymon", "blackWarGrowlmon"], method: "-" , icon: "./assets/growlmonorange.png" },
  greymonBlue: { name: "Greymon (Blue)", stage: "Champion", evolvesTo: ["metalGreymonBlue", "skullGreymon", "gigadramon"], method: "-" , icon: "./assets/greymonblue.png" },
  garurumonBlack: { name: "Garurumon (Black)", stage: "Champion", evolvesTo: ["wereGarurumonBlack", "doumon", "etemon"], method: "-" , icon: "./assets/garurumonblack.png" },
  redVegiemon: { name: "RedVegiemon", stage: "Champion", evolvesTo: ["lillymon", "warGrowlmonOrange", "megaKabuterimon"], method: "-" , icon: "./assets/redvegiemon.png" },
  iceDevimon: { name: "IceDevimon", stage: "Champion", evolvesTo: ["gigadramon", "zudomon", "taomonSilver"], method: "-" , icon: "./assets/icedevimon.png" },
  sorcermon: { name: "Sorcermon", stage: "Champion", evolvesTo: ["iceLeomon", "magnaAngemon", "blueMeramon"], method: "-" , icon: "./assets/sorcermon.png" },
  chrysalimon: { name: "Chrysalimon", stage: "Champion", evolvesTo: ["infermon", "datamon", "megaKabuterimonBlue"], method: "-" , icon: "./assets/chrysalimon.png" },
  numemon: { name: "Numemon", stage: "Champion", evolvesTo: ["monzaemon"], method: "-" , icon: "./assets/numemon.png" },
  geremon: { name: "Geremon", stage: "Champion", evolvesTo: ["etemon"], method: "-" , icon: "./assets/geremon.png" },
  sukamon: { name: "Sukamon", stage: "Champion", evolvesTo: [], method: "-" , icon: "./assets/sukamon.png" },
  platinumSukamon: { name: "PlatinumSukamon", stage: "Champion", evolvesTo: [], method: "-" , icon: "./assets/platinumsukamon.png" },
  meicoomon: { name: "Meicoomon", stage: "Champion", evolvesTo: ["maycrackmonVm", "ladyDevimon", "angewomon"], method: "-" , icon: "./assets/meicoomon.png" },
  metalGreymon: { name: "MetalGreymon", stage: "Ultimate", evolvesTo: ["warGreymon", "shineGreymon", "kaiserGreymon", "alphamon"], method: "-" , icon: "./assets/metalgreymon.png" },
  wereGarurumon: { name: "WereGarurumon", stage: "Ultimate", evolvesTo: ["metalGarurumon", "jijimon", "magnaGarurumon", "leopardmon"], method: "-" , icon: "./assets/weregarurumon.png" },
  garudamon: { name: "Garudamon", stage: "Ultimate", evolvesTo: ["phoenixmon", "magnadramon", "beelzemon", "justimon"], method: "-" , icon: "./assets/garudamon.png" },
  magnaAngemon: { name: "MagnaAngemon", stage: "Ultimate", evolvesTo: ["seraphimon", "cherubimon", "jesmon", "marineAngemon"], method: "-" , icon: "./assets/magnaangemon.png" },
  megaKabuterimon: { name: "MegaKabuterimon", stage: "Ultimate", evolvesTo: ["herculesKabuterimon", "chaosGallantmon", "craniamon"], method: "-" , icon: "./assets/megakabuterimon.png" },
  zudomon: { name: "Zudomon", stage: "Ultimate", evolvesTo: ["vikemon", "metalSeadramon", "titamon", "boltmon"], method: "-" , icon: "./assets/zudomon.png" },
  lillymon: { name: "Lillymon", stage: "Ultimate", evolvesTo: ["rosemon", "sakuyamon", "lilithmon", "minervamon"], method: "-" , icon: "./assets/lillymon.png" },
  angewomon: { name: "Angewomon", stage: "Ultimate", evolvesTo: ["magnadramon", "ophanimon", "crusadermon", "marineAngemon"], method: "-" , icon: "./assets/angewomon.png" },
  paildramon: { name: "Paildramon", stage: "Ultimate", evolvesTo: ["magnamon", "imperialdramonDm", "ulForceVeedramon"], method: "-" , icon: "./assets/paildramon.png" },
  warGrowlmon: { name: "WarGrowlmon", stage: "Ultimate", evolvesTo: ["gallantmon", "shineGreymon", "leviamon", "kaiserGreymon"], method: "-" , icon: "./assets/wargrowlmon.png" },
  rapidmon: { name: "Rapidmon", stage: "Ultimate", evolvesTo: ["megaGargomon", "vikemon", "magnaGarurumon", "kentaurosmon"], method: "-" , icon: "./assets/rapidmon.png" },
  antylamon: { name: "Antylamon", stage: "Ultimate", evolvesTo: ["cherubimon", "ophanimon", "belphemonSm"], method: "-" , icon: "./assets/antylamon.png" },
  taomon: { name: "Taomon", stage: "Ultimate", evolvesTo: ["sakuyamon", "dianamon", "arresterdramon", "barbamon"], method: "-" , icon: "./assets/taomon.png" },
  machGaogamon: { name: "MachGaogamon", stage: "Ultimate", evolvesTo: ["mirageGaogamon", "metalGarurumon", "gankoomon", "justimon"], method: "-" , icon: "./assets/machgaogamon.png" },
  aeroVeedramon: { name: "AeroVeedramon", stage: "Ultimate", evolvesTo: ["ulForceVeedramon", "omniShoutmon", "jesmon", "darkdramon"], method: "-" , icon: "./assets/aeroveedramon.png" },
  myotismon: { name: "Myotismon", stage: "Ultimate", evolvesTo: ["venomMyotismon", "jijimon", "barbamon", "piedmon", "boltboutamon"], method: "-" , icon: "./assets/myotismon.png" },
  ladyDevimon: { name: "LadyDevimon", stage: "Ultimate", evolvesTo: ["lilithmon", "rosemon", "kuzuhamon", "piedmon"], method: "-" , icon: "./assets/ladydevimon.png" },
  mamemon: { name: "Mamemon", stage: "Ultimate", evolvesTo: ["kentaurosmon", "platinumNumemon", "justimon", "jijimon"], method: "-" , icon: "./assets/mamemon.png" },
  metalMamemon: { name: "MetalMamemon", stage: "Ultimate", evolvesTo: ["dynasmon", "machinedramon", "magnaGarurumon", "metalGarurumon"], method: "-" , icon: "./assets/metalmamemon.png" },
  lucemonFm: { name: "Lucemon FM", stage: "Ultimate", evolvesTo: ["lucemonSm", "venomMyotismon", "seraphimon"], method: "-" , icon: "./assets/lucemonfm.png" },
  metalTyrannomon: { name: "MetalTyrannomon", stage: "Ultimate", evolvesTo: ["metalGarurumon", "jijimon", "magnaGarurumon", "leopardmon"], method: "-" , icon: "./assets/metaltyrannomon.png" },
  skullGreymon: { name: "SkullGreymon", stage: "Ultimate", evolvesTo: ["titamon", "craniamon", "blackWarGreymon"], method: "-" , icon: "./assets/skullgreymon.png" },
  gigadramon: { name: "Gigadramon", stage: "Ultimate", evolvesTo: ["machinedramon", "rustTyrannomon", "justimon", "dynasmon"], method: "-" , icon: "./assets/gigadramon.png" },
  megadramon: { name: "Megadramon", stage: "Ultimate", evolvesTo: ["darkdramon", "arresterdramon", "warGreymon", "belphemonSm"], method: "-" , icon: "./assets/megadramon.png" },
  iceLeomon: { name: "IceLeomon", stage: "Ultimate", evolvesTo: ["gankoomon", "magnadramon", "banchoLeomon"], method: "-" , icon: "./assets/iceleomon.png" },
  grapLeomon: { name: "GrapLeomon", stage: "Ultimate", evolvesTo: ["banchoLeomon", "megaGargomon", "dynasmon"], method: "-" , icon: "./assets/grapleomon.png" },
  blueMeramon: { name: "BlueMeramon", stage: "Ultimate", evolvesTo: ["leviamon", "mirageGaogamon", "boltmon", "gankoomon"], method: "-" , icon: "./assets/bluemeramon.png" },
  megaSeadramon: { name: "MegaSeadramon", stage: "Ultimate", evolvesTo: ["metalSeadramon", "marineAngemon", "machinedramon", "leviamon"], method: "-" , icon: "./assets/megaseadramon.png" },
  okuwamon: { name: "Okuwamon", stage: "Ultimate", evolvesTo: ["granKuwagamon", "examon", "diaboromon"], method: "-" , icon: "./assets/okuwamon.png" },
  datamon: { name: "Datamon", stage: "Ultimate", evolvesTo: ["barbamon", "platinumNumemon", "metalGarurumonBlack"], method: "-" , icon: "./assets/datamon.png" },
  meteormon: { name: "Meteormon", stage: "Ultimate", evolvesTo: ["belphemonSm", "cherubimon", "dianamon", "metalEtemon"], method: "-" , icon: "./assets/meteormon.png" },
  metalGreymonBlue: { name: "MetalGreymon (Blue)", stage: "Ultimate", evolvesTo: ["blackWarGreymon", "samudramon", "alphamon", "boltmon"], method: "-" , icon: "./assets/metalgreymonblue.png" },
  wereGarurumonBlack: { name: "WereGarurumon (Black)", stage: "Ultimate", evolvesTo: ["metalGarurumon", "jijimon", "magnaGarurumon", "leopardmon"], method: "-" , icon: "./assets/weregarurumonblack.png" },
  megaKabuterimonBlue: { name: "MegaKabuterimon (Blue)", stage: "Ultimate", evolvesTo: ["craniamon", "granKuwagamon", "kentaurosmon"], method: "-" , icon: "./assets/megakabuterimonblue.png" },
  warGrowlmonOrange: { name: "WarGrowlmon (Orange)", stage: "Ultimate", evolvesTo: ["examon", "rustTyrannomon", "warGreymon"], method: "-" , icon: "./assets/wargrowlmonorange.png" },
  blackWarGrowlmon: { name: "BlackWarGrowlmon", stage: "Ultimate", evolvesTo: ["chaosGallantmon", "beelzemon", "darkdramon", "samudramon"], method: "-" , icon: "./assets/blackwargrowlmon.png" },
  rapidmonGold: { name: "Rapidmon (Gold)", stage: "Ultimate", evolvesTo: ["omniShoutmon", "herculesKabuterimon", "magnamon"], method: "-" , icon: "./assets/rapidmongold.png" },
  taomonSilver: { name: "Taomon (Silver)", stage: "Ultimate", evolvesTo: ["crusadermon", "phoenixmon", "kuzuhamon", "dianamon"], method: "-" , icon: "./assets/taomonsilver.png" },
  doumon: { name: "Doumon", stage: "Ultimate", evolvesTo: ["kuzuhamon", "metalGarurumonBlack", "piedmon", "lilithmon"], method: "-" , icon: "./assets/doumon.png" },
  waruSeadramon: { name: "WaruSeadramon", stage: "Ultimate", evolvesTo: ["creepymon", "metalSeadramon", "metalEtemon"], method: "-" , icon: "./assets/waruseadramon.png" },
  infermon: { name: "Infermon", stage: "Ultimate", evolvesTo: ["diaboromon", "creepymon", "venomMyotismon"], method: "-" , icon: "./assets/infermon.png" },
  etemon: { name: "Etemon", stage: "Ultimate", evolvesTo: ["metalEtemon", "megaGargomon", "platinumNumemon"], method: "-" , icon: "./assets/etemon.png" },
  monzaemon: { name: "Monzaemon", stage: "Ultimate", evolvesTo: ["platinumNumemon", "seraphimon", "minervamon", "vikemon"], method: "-" , icon: "./assets/monzaemon.png" },
  maycrackmonVm: { name: "Maycrackmon VM", stage: "Ultimate", evolvesTo: ["mastemon", "ophanimon", "rosemon"], method: "-" , icon: "./assets/maycrackmonvm.png" },
  agunimon: { name: "Agunimon", stage: "Ultimate", evolvesTo: ["kaiserGreymon", "gallantmon", "phoenixmon", "shineGreymon"], method: "-" , icon: "./assets/agunimon.png" },
  warGreymon: { name: "WarGreymon", stage: "Mega", evolvesTo: ["omegamon"], method: "-" , icon: "./assets/wargreymon.png" },
  shineGreymon: { name: "ShineGreymon", stage: "Mega", evolvesTo: ["shineGreymonBM"], method: "-" , icon: "./assets/shinegreymon.png" },
  metalGarurumon: { name: "MetalGarurumon", stage: "Mega", evolvesTo: ["omegamon"], method: "-" , icon: "./assets/metalgarurumon.png" },
  phoenixmon: { name: "Phoenixmon", stage: "Mega", evolvesTo: ["imperialdramonFM"], method: "-" , icon: "./assets/phoenixmon.png" },
  seraphimon: { name: "Seraphimon", stage: "Mega", evolvesTo: ["imperialdramonFM"], method: "-" , icon: "./assets/seraphimon.png" },
  herculesKabuterimon: { name: "HerculesKabuterimon", stage: "Mega", evolvesTo: ["imperialdramonFM"], method: "-" , icon: "./assets/herculeskabuterimon.png" },
  vikemon: { name: "Vikemon", stage: "Mega", evolvesTo: [], method: "-" , icon: "./assets/vikemon.png" },
  rosemon: { name: "Rosemon", stage: "Mega", evolvesTo: ["rosemonBurstMode", "imperialdramonFM"], method: "-" , icon: "./assets/rosemon.png" },
  magnadramon: { name: "Magnadramon", stage: "Mega", evolvesTo: ["imperialdramonFM"], method: "-" , icon: "./assets/magnadramon.png" },
  marineAngemon: { name: "MarineAngemon", stage: "Mega", evolvesTo: ["omegamonZwartD"], method: "-" , icon: "./assets/marineangemon.png" },
  magnamon: { name: "Magnamon", stage: "Mega", evolvesTo: ["imperialdramonPM"], method: "-" , icon: "./assets/magnamon.png" },
  gallantmon: { name: "Gallantmon", stage: "Mega", evolvesTo: ["gallantmonCM"], method: "-" , icon: "./assets/gallantmon.png" },
  megaGargomon: { name: "MegaGargomon", stage: "Mega", evolvesTo: [], method: "-" , icon: "./assets/megagargomon.png" },
  cherubimon: { name: "Cherubimon", stage: "Mega", evolvesTo: [], method: "-" , icon: "./assets/cherubimon.png" },
  sakuyamon: { name: "Sakuyamon", stage: "Mega", evolvesTo: ["rosemonBurstMode"], method: "-" , icon: "./assets/sakuyamon.png" },
  mirageGaogamon: { name: "MirageGaogamon", stage: "Mega", evolvesTo: ["shineGreymonBM"], method: "-" , icon: "./assets/miragegaogamon.png" },
  ulForceVeedramon: { name: "UlforceVeedramon", stage: "Mega", evolvesTo: ["gallantmonCM"], method: "-" , icon: "./assets/ulforceveedramon.png" },
  venomMyotismon: { name: "VenomMyotismon", stage: "Mega", evolvesTo: ["omegamonZwartD"], method: "-" , icon: "./assets/venommyotismon.png" },
  lilithmon: { name: "Lilithmon", stage: "Mega", evolvesTo: ["belphemonRM"], method: "-" , icon: "./assets/lilithmon.png" },
  justimon: { name: "Justimon", stage: "Mega", evolvesTo: ["omegamonZwartD"], method: "-" , icon: "./assets/justimon.png" },
  piedmon: { name: "Piedmon", stage: "Mega", evolvesTo: ["boltboutamon", "armageddemon"], method: "-" , icon: "./assets/piedmon.png" },
  lucemonSm: { name: "Lucemon SM", stage: "Mega", evolvesTo: ["belphemonRM"], method: "-" , icon: "./assets/lucemonsm.png" },
  rustTyrannomon: { name: "RustTyranomon", stage: "Mega", evolvesTo: ["omegamonZwartD"], method: "-" , icon: "./assets/rusttyranomon.png" },
  samudramon: { name: "Samudramon", stage: "Mega", evolvesTo: ["omegamonAlterB"], method: "-" , icon: "./assets/samudramon.png" },
  machinedramon: { name: "Machinedramon", stage: "Mega", evolvesTo: ["armageddemon"], method: "-" , icon: "./assets/machinedramon.png" },
  beelzemon: { name: "Beelzemon", stage: "Mega", evolvesTo: [], method: "-" , icon: "./assets/beelzemon.png" },
  banchoLeomon: { name: "BanchoLeomon", stage: "Mega", evolvesTo: ["chaosmon"], method: "-" , icon: "./assets/bancholeomon.png" },
  leviamon: { name: "Leviamon", stage: "Mega", evolvesTo: [], method: "-" , icon: "./assets/leviamon.png" },
  crusadermon: { name: "Crusadermon", stage: "Mega", evolvesTo: [], method: "-" , icon: "./assets/crusadermon.png" },
  boltmon: { name: "Boltmon", stage: "Mega", evolvesTo: ["omegamonZwartD"], method: "-" , icon: "./assets/boltmon.png" },
  creepymon: { name: "Creepymon", stage: "Mega", evolvesTo: ["belphemonRM"], method: "-" , icon: "./assets/creepymon.png" },
  metalSeadramon: { name: "MetalSeadramon", stage: "Mega", evolvesTo: ["armageddemon"], method: "-" , icon: "./assets/metalseadramon.png" },
  granKuwagamon: { name: "GranKuwagamon", stage: "Mega", evolvesTo: ["omegamonZwartD"], method: "-" , icon: "./assets/grankuwagamon.png" },
  belphemonSm: { name: "Belphemon SM", stage: "Mega", evolvesTo: ["belphemonRM"], method: "-" , icon: "./assets/belphemonsm.png" },
  barbamon: { name: "Barbamon", stage: "Mega", evolvesTo: ["belphemonRM"], method: "-" , icon: "./assets/barbamon.png" },
  examon: { name: "Examon", stage: "Mega", evolvesTo: ["gallantmonCM"], method: "-" , icon: "./assets/examon.png" },
  titamon: { name: "Titamon", stage: "Mega", evolvesTo: ["omegamonAlterB"], method: "-" , icon: "./assets/titamon.png" },
  gankoomon: { name: "Gankoomon", stage: "Mega", evolvesTo: [], method: "-" , icon: "./assets/gankoomon.png" },
  kentaurosmon: { name: "Kentaurosmon", stage: "Mega", evolvesTo: ["gallantmonCM"], method: "-" , icon: "./assets/kentaurosmon.png" },
  craniamon: { name: "Craniamon", stage: "Mega", evolvesTo: [], method: "-" , icon: "./assets/craniamon.png" },
  blackWarGreymon: { name: "BlackWarGreymon", stage: "Mega", evolvesTo: ["omegamonZwart"], method: "-" , icon: "./assets/blackwargreymon.png" },
  metalGarurumonBlack: { name: "MetalGarurumon (Black)", stage: "Mega", evolvesTo: ["omegamonZwart"], method: "-" , icon: "./assets/metalgarurumonblack.png" },
  chaosGallantmon: { name: "ChaosGallantmon", stage: "Mega", evolvesTo: ["gallantmonCM"], method: "-" , icon: "./assets/chaosgallantmon.png" },
  kuzuhamon: { name: "Kuzuhamon", stage: "Mega", evolvesTo: ["omegamonAlterB"], method: "-" , icon: "./assets/kuzuhamon.png" },
  diaboromon: { name: "Diaboromon", stage: "Mega", evolvesTo: ["armageddemon"], method: "-" , icon: "./assets/diaboromon.png" },
  metalEtemon: { name: "MetalEtemon", stage: "Mega", evolvesTo: ["omegamonAlterB"], method: "-" , icon: "./assets/metaletemon.png" },
  platinumNumemon: { name: "PlatinumNumemon", stage: "Mega", evolvesTo: ["omegamonZwartD"], method: "-" , icon: "./assets/platinumnumemon.png" },
  ophanimon: { name: "Ophanimon", stage: "Mega", evolvesTo: ["rosemonBurstMode"], method: "-" , icon: "./assets/ophanimon.png" },
  imperialdramonDm: { name: "Imperialdramon DM", stage: "Mega", evolvesTo: ["imperialdramonPM", "imperialdramonFM"], method: "-" , icon: "./assets/imperialdramondm.png" },
  leopardmon: { name: "Leopardmon", stage: "Mega", evolvesTo: [], method: "-" , icon: "./assets/leopardmon.png" },
  dynasmon: { name: "Dynasmon", stage: "Mega", evolvesTo: ["gallantmonCM"], method: "-" , icon: "./assets/dynasmon.png" },
  jijimon: { name: "Jijimon", stage: "Mega", evolvesTo: ["omegamonZwartD"], method: "-" , icon: "./assets/jijimon.png" },
  mastemon: { name: "Mastemon", stage: "Mega", evolvesTo: ["rosemonBurstMode"], method: "-" , icon: "./assets/mastemon.png" },
  alphamon: { name: "Alphamon", stage: "Mega", evolvesTo: ["gallantmonCM"], method: "-" , icon: "./assets/alphamon.png" },
  jesmon: { name: "Jesmon", stage: "Mega", evolvesTo: ["gallantmonCM"], method: "-" , icon: "./assets/jesmon.png" },
  minervamon: { name: "Minervamon", stage: "Mega", evolvesTo: [], method: "-" , icon: "./assets/minervamon.png" },
  dianamon: { name: "Dianamon", stage: "Mega", evolvesTo: ["rosemonBurstMode"], method: "-" , icon: "./assets/dianamon.png" },
  darkdramon: { name: "Darkdramon", stage: "Mega", evolvesTo: ["chaosmon"], method: "-" , icon: "./assets/darkdramon.png" },
  kaiserGreymon: { name: "KaiserGreymon", stage: "Mega", evolvesTo: ["susanoomon"], method: "-" , icon: "./assets/kaisergreymon.png" },
  magnaGarurumon: { name: "MagnaGarurumon", stage: "Mega", evolvesTo: ["susanoomon"], method: "-" , icon: "./assets/magnagarurumon.png" },
  arresterdramon: { name: "Arresterdramon", stage: "Mega", evolvesTo: ["omegamonAlterB"], method: "-" , icon: "./assets/arresterdramon.png" },
  omniShoutmon: { name: "OmniShoutmon", stage: "Mega", evolvesTo: ["omegamonAlterB"], method: "-" , icon: "./assets/omnishoutmon.png" },
  omegamon: { name: "Omegamon", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/omegamon.png" },
  omegamonZwart: { name: "Omegamon Zwart", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/omegamonzwart.png" },
  imperialdramonFM: { name: "Imperialdramon FM", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/imperialdramonfm.png" },
  imperialdramonPM: { name: "Imperialdramon PM", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/imperialdramonpm.png" },
  susanoomon: { name: "Susanoomon", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/susanoomon.png" },
  belphemonRM: { name: "Belphemon RM", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/belphemonrm.png" },
  omegamonZwartD: { name: "Omegamon Zwart D", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/omegamonzwartd.png" },
  armageddemon: { name: "Armageddemon", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/armageddemon.png" },
  omegamonAlterB: { name: "Omegamon Alter-B", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/omegamonalterb.png" },
  gallantmonCM: { name: "Gallantmon CM", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/gallantmoncm.png" },
  shineGreymonBM: { name: "ShineGreymon BM", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/shinegreymonbm.png" },
  rosemonBurstMode: { name: "Rosemon Burst Mode", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/rosemonburstmode.png" },
  chaosmon: { name: "Chaosmon", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/chaosmon.png" },
  boltboutamon: { name: "Boltboutamon", stage: "Mega DNA", evolvesTo: [], method: "-" , icon: "./assets/boltboutamon.png" }
};
