/**
 * Simple JSON defining Digivolution.
 * Each Digimon knows only its direct evolutions.
 */
const DIGIMONS = {
  botamon: { name:"Botamon", stage:"Baby", evolvesTo:["koromon"], method:"-" },
  punimon: { name:"Punimon", stage:"Baby", evolvesTo:["tsunomon"], method:"-" },
  poyomon: { name:"Poyomon", stage:"Baby", evolvesTo:["tokomon"], method:"-" },
  conomon: { name:"Conomon", stage:"Baby", evolvesTo:["kokomon"], method:"-" },
  yukimiBotamon: { name:"YukimiBotamon", stage:"Baby", evolvesTo:["nyaromon"], method:"-" },
  pabumon: { name:"Pabumon", stage:"Baby", evolvesTo:["motimon"], method:"-" },
  jyarimon: { name:"Jyarimon", stage:"Baby", evolvesTo:["gigimon"], method:"-" },
  zerimon: { name:"Zerimon", stage:"Baby", evolvesTo:["gummymon"], method:"-" },
  kuramon: { name:"Kuramon", stage:"Baby", evolvesTo:["tsumemon"], method:"-" },
  pichimon: { name:"Pichimon", stage:"Baby", evolvesTo:["bukamon"], method:"-" },
  yuramon: { name:"Yuramon", stage:"Baby", evolvesTo:["tanemon"], method:"-" },
  koromon: { name:"Koromon", stage:"In-Training", evolvesTo:["agumon","toyAgumon", "agumonBlack", "veemon", "shoutmon"], method:"-" },
  tsunomon: { name:"Tsunomon", stage:"In-Training", evolvesTo:["gabumon","gaomon", "psychemon", "gabumonBlack", "gumdramon"], method:"-" },
  tokomon: { name:"Tokomon", stage:"In-Training", evolvesTo:["patamon","biyomon", "tsukaimon", "hackmon", "lucemon"], method:"-" },
  motimon: { name:"Motimon", stage:"In-Training", evolvesTo:["tentomon","wormmon", "gotsumon", "hackmon", "hagurumon"], method:"-" },
  tanemon: { name:"Tanemon", stage:"In-Training", evolvesTo:["palmon","renamon", "aruraumon", "goblimon", "demiDevimon"], method:"-" },
  gigimon: { name:"Gigimon", stage:"In-Training", evolvesTo:["guilmon","goblimon", "solarmon", "gotsumon", "shoutmon"], method:"-" },
  gummymon: { name:"Gummymon", stage:"In-Training", evolvesTo:["terriermon","toyAgumon", "clearAgumon", "hagurumon", "gaomon"], method:"-" },
  kokomon: { name:"Kokomon", stage:"In-Training", evolvesTo:["lopmon","demiDevimon", "shamamon", "toyAgumonBlack", "wormmon"], method:"-" },
  tsumemon: { name:"Tsumemon", stage:"In-Training", evolvesTo:["keramon", "toyAgumonBlack", "agumonBlack", "gabumonBlack", "tsukaimon"], method:"-" },
  nyaromon: { name:"Nyaromon", stage:"In-Training", evolvesTo:["salamon","snowAgumon", "renamon", "biyomon", "lucemon"], method:"-" },
  bukamon: { name:"Bukamon", stage:"In-Training", evolvesTo:["gomamon","veemon", "snowGoblimon", "clearAgumon", "gumdramon"], method:"-" },
  agumon: { name:"Agumon", stage:"Rookie", evolvesTo:["greymon","tyrannomon", "meramon", "greymonBlue"], method:"-" },
  gabumon: { name:"Gabumon", stage:"Rookie", evolvesTo:["garurumon", "gaoGamon", "garurumonBlack", "seadramon"], method:"-" },
  biyomon: { name:"Biyomon", stage:"Rookie", evolvesTo:["birdramon", "piddomon", "redVeedramon", "youkomon"], method:"-" },
  patamon: { name:"Patamon", stage:"Rookie", evolvesTo:["angemon", "piddomon", "veedramon", "growlmonOrange"], method:"-" },
  tentomon: { name:"Tentomon", stage:"Rookie", evolvesTo:["kabuterimon", "redVegiemon", "woodmon", "bomberNanimon"], method:"-" },
  gomamon: { name:"Gomamon", stage:"Rookie", evolvesTo:["ikkakumon", "seadramon", "icemon", "sorcermon"], method:"-" },
  palmon: { name:"Palmon", stage:"Rookie", evolvesTo:["togemon", "woodmon", "vegiemon", "redVegiemon"], method:"-" },
  salamon: { name:"Salamon", stage:"Rookie", evolvesTo:["gatomon", "blackGatomon", "gargomon", "meicoomon"], method:"-" },
  veemon: { name:"Veemon", stage:"Rookie", evolvesTo:["exVeemon", "veedramon", "meramon", "goldVeedramon"], method:"-" },
  wormmon: { name:"Wormmon", stage:"Rookie", evolvesTo:["stingmon", "kuwagamon", "kabuterimon", "devimon"], method:"-" },
  guilmon: { name:"Guilmon", stage:"Rookie", evolvesTo:["growlmon", "growlmonOrange", "tyrannomon", "redVeedramon"], method:"-" },
  terriermon: { name:"Terriermon", stage:"Rookie", evolvesTo:["gargomon", "ikkakumon", "angemon", "ogremon"], method:"-" },
  lopmon: { name:"Lopmon", stage:"Rookie", evolvesTo:["turuiemon", "kyubimonSilver", "wizardmon", "blackGatomon"], method:"-" },
  renamon: { name:"Renamon", stage:"Rookie", evolvesTo:["kyubimon", "kyubimonSilver", "turuiemon", "leomon"], method:"-" },
  gaomon: { name:"Gaomon", stage:"Rookie", evolvesTo:["gaoGamon", "garurumon", "leomon", "togemon"], method:"-" },
  hagurumon: { name:"Hagurumon", stage:"Rookie", evolvesTo:["guardomon", "goldVeedramon", "kuwagamon", "bomberNanimon"], method:"-" },
  gotsumon: { name:"Gotsumon", stage:"Rookie", evolvesTo:["icemon", "ogremon", "tyrannomon", "nanimon"], method:"-" },
  goblimon: { name:"Goblimon", stage:"Rookie", evolvesTo:["ogremon", "nanimon", "woodmon", "gaoGamon"], method:"-" },
  toyAgumon: { name:"ToyAgumon", stage:"Rookie", evolvesTo:["wizardmon", "greymon", "guardomonGold", "growlmonOrange"], method:"-" },
  demiDevimon: { name:"DemiDevimon", stage:"Rookie", evolvesTo:["devimon", "blackGatomon", "iceDevimon", "chrysalimon"], method:"-" },
  lucemon: { name:"Lucemon", stage:"Rookie", evolvesTo:["iceDevimon", "piddomon", "wizardmon", "chrysalimon"], method:"-" },
  hackmon: { name:"Hackmon", stage:"Rookie", evolvesTo:["leomon", "gururumon", "exVeemon", "goldVeedramon"], method:"-" },
  agumonBlack: { name:"Agumon (Black)", stage:"Rookie", evolvesTo:["greymonBlue", "growlmon", "saberdramon", "fugamon"], method:"-" },
  snowAgumon: { name:"SnowAgumon", stage:"Rookie", evolvesTo:["sorcermon", "gatomon", "hyogamon", "icemon"], method:"-" },
  gabumonBlack: { name:"Gabumon (Black)", stage:"Rookie", evolvesTo:["garurumonBlack", "stingmon", "gururumon", "saberdramon"], method:"-" },
  psychemon: { name:"Psychemon", stage:"Rookie", evolvesTo:["gururumon", "kyubimon", "bomberNanimon", "gargomon"], method:"-" },
  tsukaimon: { name:"Tsukaimon", stage:"Rookie", evolvesTo:["saberdramon", "devimon", "youkomon", "garurumonBlack"], method:"-" },
  aruraumon: { name:"Aruraumon", stage:"Rookie", evolvesTo:["vegiemon", "youkomon", "togemon", "stingmon"], method:"-" },
  toyAgumonBlack: { name:"ToyAgumon (Black)", stage:"Rookie", evolvesTo:["nanimon", "guardomon", "fugamon", "greymonBlue"], method:"-" },
  clearAgumon: { name:"ClearAgumon", stage:"Rookie", evolvesTo:["guardomonGold", "iceDevimon", "exVeemon", "hyogamon"], method:"-" },
  solarmon: { name:"Solarmon", stage:"Rookie", evolvesTo:["meramon", "redVegiemon", "birdramon", "guardomonGold"], method:"-" },
  snowGoblimon: { name:"SnowGoblimon", stage:"Rookie", evolvesTo:["hyogamon", "ikkakumon", "seadramon", "kyubimonSilver"], method:"-" },
  shamamon: { name:"Shamamon", stage:"Rookie", evolvesTo:["fugamon", "vegiemon", "kuwagamon", "sorcermon"], method:"-" },
  keramon: { name:"Keramon", stage:"Rookie", evolvesTo:["chrysalimon", "guardomon", "meicoomon", "kabuterimon"], method:"-" },
  gumdramon: { name:"Gumdramon", stage:"Rookie", evolvesTo:["arresterdramon", "veedramon", "turuiemon", "gatomon"], method:"-" },
  shoutmon: { name:"Shoutmon", stage:"Rookie", evolvesTo:["omniShoutmon", "growlmon", "greymon", "redVeedramon"], method:"-" },
  greymon: { name:"Greymon", stage:"Champion", evolvesTo:["metalGreymon", "metalGreymonBlue", "warGrowlmonOrange"], method:"-" },
  garurumon: { name:"Garurumon", stage:"Champion", evolvesTo:["wereGarurumon", "grapLeomon", "machGaogamon"], method:"-" },
  birdramon: { name:"Birdramon", stage:"Champion", evolvesTo:["garudamon", "aeroVeedramon", "agunimon"], method:"-" },
  angemon: { name:"Angemon", stage:"Champion", evolvesTo:["magnaAngemon", "blueMeramon", "taomon"], method:"-" },
  kabuterimon: { name:"Kabuterimon", stage:"Champion", evolvesTo:["megaKabuterimon", "megaKabuterimonBlue", "skullGreymon"], method:"-" },
  ikkakumon: { name:"Ikkakumon", stage:"Champion", evolvesTo:["zudomon", "iceLeomon", "rapidmon"], method:"-" },
  togemon: { name:"Togemon", stage:"Champion", evolvesTo:["lillymon", "mamemon", "ladyDevimon"], method:"-" },
  gatomon: { name:"Gatomon", stage:"Champion", evolvesTo:["angewomon", "taomonSilver", "lillymon"], method:"-" },
  exVeemon: { name:"ExVeemon", stage:"Champion", evolvesTo:["aeroVeedramon", "metalTyrannomon", "garudamon"], method:"-" },
  stingmon: { name:"Stingmon", stage:"Champion", evolvesTo:["megaKabuterimonBlue", "okuwamon", "megaKabuterimon"], method:"-" },
  growlmon: { name:"Growlmon", stage:"Champion", evolvesTo:["warGrowlmon", "skullGreymon", "blackWarGrowlmon"], method:"-" },
  gargomon: { name:"Gargomon", stage:"Champion", evolvesTo:["rapidmon", "metalMamemon", "rapidmonGold"], method:"-" },
  turuiemon: { name:"Turuiemon", stage:"Champion", evolvesTo:["antylamon", "megadramon", "monzaemon"], method:"-" },
  kyubimon: { name:"Kyubimon", stage:"Champion", evolvesTo:["taomon", "monzaemon", "wereGarurumon"], method:"-" },
  gaoGamon: { name:"GaoGamon", stage:"Champion", evolvesTo:["machGaogamon", "wereGarurumon", "grapLeomon"], method:"-" },
  wizardmon: { name:"Wizardmon", stage:"Champion", evolvesTo:["lucemonFm", "myotismon", "magnaAngemon"], method:"-" },
  devimon: { name:"Devimon", stage:"Champion", evolvesTo:["myotismon", "doumon", "infermon"], method:"-" },
  veedramon: { name:"Veedramon", stage:"Champion", evolvesTo:["aeroVeedramon", "machGaogamon", "megaSeadramon"], method:"-" },
  tyrannomon: { name:"Tyrannomon", stage:"Champion", evolvesTo:["metalTyrannomon", "metalGreymonBlue", "warGrowlmon"], method:"-" },
  ogremon: { name:"Ogremon", stage:"Champion", evolvesTo:["skullGreymon", "waruSeadramon", "metalTyrannomon"], method:"-" },
  leomon: { name:"Leomon", stage:"Champion", evolvesTo:["grapLeomon", "rapidmon", "iceLeomon"], method:"-" },
  meramon: { name:"Meramon", stage:"Champion", evolvesTo:["blueMeramon", "garudamon", "myotismon"], method:"-" },
  vegiemon: { name:"Vegiemon", stage:"Champion", evolvesTo:["mamemon", "etemon", "okuwamon"], method:"-" },
  nanimon: { name:"Nanimon", stage:"Champion", evolvesTo:["waruSeadramon", "doumon", "etemon"], method:"-" },
  seadramon: { name:"Seadramon", stage:"Champion", evolvesTo:["megaSeadramon", "gigadramon", "waruSeadramon"], method:"-" },
  kuwagamon: { name:"Kuwagamon", stage:"Champion", evolvesTo:["okuwamon", "warGrowlmonOrange", "infermon"], method:"-" },
  guardomon: { name:"Guardomon", stage:"Champion", evolvesTo:["datamon", "metalMamemon", "metalTyrannomon"], method:"-" },
  woodmon: { name:"Woodmon", stage:"Champion", evolvesTo:["okuwamon", "taomon", "mamemon"], method:"-" },
  bomberNanimon: { name:"BomberNanimon", stage:"Champion", evolvesTo:["megadramon", "meteormon", "metalMamemon"], method:"-" },
  icemon: { name:"Icemon", stage:"Champion", evolvesTo:["meteormon", "mamemon", "zudomon"], method:"-" },
  hyogamon: { name:"Hyogamon", stage:"Champion", evolvesTo:["blueMeramon", "zudomon", "iceLeomon"], method:"-" },
  piddomon: { name:"Piddomon", stage:"Champion", evolvesTo:["meteormon", "angewomon", "monzaemon"], method:"-" },
  kyubimonSilver: { name:"Kyubimon (Silver)", stage:"Champion", evolvesTo:["taomonSilver", "gigadramon", "antylamon"], method:"-" },
  gururumon: { name:"Gururumon", stage:"Champion", evolvesTo:["blackWarGrowlmon", "wereGarurumonBlack", "taomonSilver"], method:"-" },
  saberdramon: { name:"Saberdramon", stage:"Champion", evolvesTo:["megadramon", "waruSeadramon", "ladyDevimon"], method:"-" },
  blackGatomon: { name:"BlackGatomon", stage:"Champion", evolvesTo:["ladyDevimon", "antylamon", "maycrackmonVm"], method:"-" },
  fugamon: { name:"Fugamon", stage:"Champion", evolvesTo:["blackWarGrowlmon", "garudamon", "machGaogamon"], method:"-" },
  guardomonGold: { name:"Guardomon (Gold)", stage:"Champion", evolvesTo:["metalMamemon", "datamon", "rapidmonGold"], method:"-" },
  youkomon: { name:"Youkomon", stage:"Champion", evolvesTo:["doumon", "megaKabuterimonBlue", "wereGarurumonBlack"], method:"-" },
  redVeedramon: { name:"RedVeedramon", stage:"Champion", evolvesTo:["warGrowlmon", "megaKabuterimon", "agunimon"], method:"-" },
  goldVeedramon: { name:"GoldVeedramon", stage:"Champion", evolvesTo:["megaSeadramon", "metalGreymon", "rapidmonGold"], method:"-" },
  growlmonOrange: { name:"Growlmon (Orange)", stage:"Champion", evolvesTo:["warGrowlmonOrange", "metalGreymon", "blackWarGrowlmon"], method:"-" },
  greymonBlue: { name:"Greymon (Blue)", stage:"Champion", evolvesTo:["metalGreymonBlue", "skullGreymon", "gigadramon"], method:"-" },
  garurumonBlack: { name:"Garurumon (Black)", stage:"Champion", evolvesTo:["wereGarurumonBlack", "doumon", "etemon"], method:"-" },
  redVegiemon: { name:"RedVegiemon", stage:"Champion", evolvesTo:["lillymon", "warGrowlmonOrange", "megaKabuterimon"], method:"-" },
  iceDevimon: { name:"IceDevimon", stage:"Champion", evolvesTo:["gigadramon", "zudomon", "taomonSilver"], method:"-" },
  sorcermon: { name:"Sorcermon", stage:"Champion", evolvesTo:["iceLeomon", "magnaAngemon", "blueMeramon"], method:"-" },
  chrysalimon: { name:"Chrysalimon", stage:"Champion", evolvesTo:["infermon", "datamon", "megaKabuterimonBlue"], method:"-" },
  numemon: { name:"Numemon", stage:"Champion", evolvesTo:["monzaemon"], method:"-" },
  geremon: { name:"Geremon", stage:"Champion", evolvesTo:["etemon"], method:"-" },
  sukamon: { name:"Sukamon", stage:"Champion", evolvesTo:[], method:"-" },
  platinumSukamon: { name:"PlatinumSukamon", stage:"Champion", evolvesTo:[], method:"-" },
  meicoomon: { name:"Meicoomon", stage:"Champion", evolvesTo:["maycrackmonVm", "ladyDevimon", "angewomon"], method:"-" },
  metalGreymon: { name:"MetalGreymon", stage:"Ultimate", evolvesTo:["warGreymon", "shineGreymon", "kaiserGreymon", "alphamon"], method:"-" },
  wereGarurumon: { name:"WereGarurumon", stage:"Ultimate", evolvesTo:["metalGarurumon", "jijimon", "magnaGarurumon", "leopardmon"], method:"-" },
  garudamon: { name:"Garudamon", stage:"Ultimate", evolvesTo:["phoenixmon", "magnadramon", "beelzemon", "justimon"], method:"-" },
  magnaAngemon: { name:"MagnaAngemon", stage:"Ultimate", evolvesTo:["seraphimon", "cherubimon", "jesmon", "marineAngemon"], method:"-" },
  megaKabuterimon: { name:"MegaKabuterimon", stage:"Ultimate", evolvesTo:["herculesKabuterimon", "chaosGallantmon", "craniamon"], method:"-" },
  zudomon: { name:"Zudomon", stage:"Ultimate", evolvesTo:["vikemon", "metalSeadramon", "titamon", "boltmon"], method:"-" },
  lillymon: { name:"Lillymon", stage:"Ultimate", evolvesTo:["rosemon", "sakuyamon", "lilithmon", "minervamon"], method:"-" },
  angewomon: { name:"Angewomon", stage:"Ultimate", evolvesTo:["magnadramon", "ophanimon", "crusadermon", "marineAngemon"], method:"-" },
  paildramon: { name:"Paildramon", stage:"Ultimate", evolvesTo:["magnamon", "imperialdramonDm", "uiForceVeedramon"], method:"-" },
  warGrowlmon: { name:"WarGrowlmon", stage:"Ultimate", evolvesTo:["gallantmon", "shineGreymon", "leviamon", "kaiserGreymon"], method:"-" },
  rapidmon: { name:"Rapidmon", stage:"Ultimate", evolvesTo:["megaGargomon", "vikemon", "magnaGarurumon", "kentaurosmon"], method:"-" },
  antylamon: { name:"Antylamon", stage:"Ultimate", evolvesTo:["cherubimon", "ophanimon", "belphemonSm"], method:"-" },
  taomon: { name:"Taomon", stage:"Ultimate", evolvesTo:["sakuyamon", "dianamon", "arresterdramon", "barbamon"], method:"-" },
  machGaogamon: { name:"MachGaogamon", stage:"Ultimate", evolvesTo:["mirageGaogamon", "metalGarurumon", "gankoomon", "justimon"], method:"-" },
  aeroVeedramon: { name:"AeroVeedramon", stage:"Ultimate", evolvesTo:["uiForceVeedramon", "omniShoutmon", "jesmon", "darkdramon"], method:"-" },
  myotismon: { name:"Myotismon", stage:"Ultimate", evolvesTo:["venomMyotismon", "jijimon", "barbamon", "piedmon", "boltboutamon"], method:"-" },
  ladyDevimon: { name:"LadyDevimon", stage:"Ultimate", evolvesTo:["lilithmon", "rosemon", "kuzuhamon", "piedmon"], method:"-" },
  mamemon: { name:"Mamemon", stage:"Ultimate", evolvesTo:["kentaurosmon", "platinumNumemon", "justimon", "jijimon"], method:"-" },
  metalMamemon: { name:"MetalMamemon", stage:"Ultimate", evolvesTo:["dynasmon", "machinedramon", "magnaGarurumon", "metalGarurumon"], method:"-" },
  lucemonFm: { name:"Lucemon FM", stage:"Ultimate", evolvesTo:["lucemonSm", "venomMyotismon", "seraphimon"], method:"-" },
  metalTyrannomon: { name:"MetalTyrannomon", stage:"Ultimate", evolvesTo:["metalGarurumon", "jijimon", "magnaGarurumon", "leopardmon"], method:"-" },
  skullGreymon: { name:"SkullGreymon", stage:"Ultimate", evolvesTo:["titamon", "craniamon", "blackWarGreymon"], method:"-" },
  gigadramon: { name:"Gigadramon", stage:"Ultimate", evolvesTo:["machinedramon", "rustTyrannomon", "justimon", "dynasmon"], method:"-" },
  megadramon: { name:"Megadramon", stage:"Ultimate", evolvesTo:["darkdramon", "arresterdramon", "warGreymon", "belphemonSm"], method:"-" },
  iceLeomon: { name:"IceLeomon", stage:"Ultimate", evolvesTo:["gankoomon", "magnadramon", "banchoLeomon"], method:"-" },
  grapLeomon: { name:"GrapLeomon", stage:"Ultimate", evolvesTo:["banchoLeomon", "megaGargomon", "dynasmon"], method:"-" },
  blueMeramon: { name:"BlueMeramon", stage:"Ultimate", evolvesTo:["leviamon", "mirageGaogamon", "boltmon", "gankoomon"], method:"-" },
  megaSeadramon: {name:"MegaSeadramon", stage:"Ultimate", evolvesTo:["metalSeadramon", "marineAngemon", "machinedramon", "leviamon"], method:"-"},
  okuwamon: { name:"Okuwamon", stage:"Ultimate", evolvesTo:["granKuwagamon", "examon", "diaboromon"], method:"-" },
  datamon: { name:"Datamon", stage:"Ultimate", evolvesTo:["barbamon", "platinumNumemon", "metalGarurumonBlack"], method:"-" },
  meteormon: { name:"Meteormon", stage:"Ultimate", evolvesTo:["belphemonSm", "cherubimon", "dianamon", "metalEtemon"], method:"-" },
  metalGreymonBlue: { name:"MetalGreymon (Blue)", stage:"Ultimate", evolvesTo:["blackWarGreymon", "samudramon", "alphamon", "boltmon"], method:"-" },
  wereGarurumonBlack: { name:"WereGarurumon (Black)", stage:"Ultimate", evolvesTo:["metalGarurumon", "jijimon", "magnaGarurumon", "leopardmon"], method:"-" },
  megaKabuterimonBlue : { name:"MegaKabuterimon (Blue)", stage:"Ultimate", evolvesTo:["craniamon", "granKuwagamon", "kentaurosmon"], method:"-" },
  warGrowlmonOrange: { name:"WarGrowlmon (Orange)", stage:"Ultimate", evolvesTo:["examon", "rustTyrannomon", "warGreymon"], method:"-" },
  blackWarGrowlmon: { name:"BlackWarGrowlmon", stage:"Ultimate", evolvesTo:["chaosGallantmon", "beelzemon", "darkdramon", "samudramon"], method:"-" },
  rapidmonGold: { name:"Rapidmon (Gold)", stage:"Ultimate", evolvesTo:["omniShoutmon", "herculesKabuterimon", "magnamon"], method:"-" },
  taomonSilver: { name:"Taomon (Silver)", stage:"Ultimate", evolvesTo:["crusadermon", "phoenixmon", "kuzuhamon", "dianamon"], method:"-" },
  doumon: { name:"Doumon", stage:"Ultimate", evolvesTo:["kuzuhamon", "metalGarurumonBlack", "piedmon", "lilithmon"], method:"-" },
  waruSeadramon: { name:"WaruSeadramon", stage:"Ultimate", evolvesTo:["creepymon", "metalSeadramon", "metalEtemon"], method:"-" },
  infermon: { name:"Infermon", stage:"Ultimate", evolvesTo:["diaboromon", "creepymon", "venomMyotismon"], method:"-" },
  etemon: { name:"Etemon", stage:"Ultimate", evolvesTo:["metalEtemon", "megaGargomon", "platinumNumemon"], method:"-" },
  monzaemon: { name:"Monzaemon", stage:"Ultimate", evolvesTo:["platinumNumemon", "seraphimon", "minervamon", "vikemon"], method:"-" },
  maycrackmonVm: { name:"Maycrackmon VM", stage:"Ultimate", evolvesTo:["mastemon", "ophanimon", "rosemon"], method:"-" },
  agunimon: { name:"Agunimon", stage:"Ultimate", evolvesTo:["kaiserGreymon", "gallantmon", "phoenixmon", "shineGreymon"], method:"-" },
  warGreymon: { name:"WarGreymon", stage:"Mega", evolvesTo:["omegamon"], method:"-" },
  shineGreymon: { name:"ShineGreymon", stage:"Mega", evolvesTo:["shineGreymonBM"], method:"-" },
  metalGarurumon: { name:"MetalGarurumon", stage:"Mega", evolvesTo:["omegamon"], method:"-" },
  phoenixmon: { name:"Phoenixmon", stage:"Mega", evolvesTo:["imperialdramonFM"], method:"-" },
  seraphimon: { name:"Seraphimon", stage:"Mega", evolvesTo:["imperialdramonFM"], method:"-" },
  herculesKabuterimon: { name:"HerculesKabuterimon", stage:"Mega", evolvesTo:["imperialdramonFM"], method:"-" },
  vikemon: { name:"Vikemon", stage:"Mega", evolvesTo:[], method:"-" },
  rosemon: { name:"Rosemon", stage:"Mega", evolvesTo:["rosemonBurstMode", "imperialdramonFM"], method:"-" },
  magnadramon: { name:"Magnadramon", stage:"Mega", evolvesTo:["imperialdramonFM"], method:"-" },
  marineAngemon: { name:"MarineAngemon", stage:"Mega", evolvesTo:["omegamonZwartD"], method:"-" },
  magnamon: { name:"Magnamon", stage:"Mega", evolvesTo:["imperialdramonPM"], method:"-" },
  gallantmon: { name:"Gallantmon", stage:"Mega", evolvesTo:["gallantmonCM"], method:"-" },
  megaGargomon: { name:"MegaGargomon", stage:"Mega", evolvesTo:[], method:"-" },
  cherubimon: { name:"Cherubimon", stage:"Mega", evolvesTo:[], method:"-" },
  sakuyamon: { name:"Sakuyamon", stage:"Mega", evolvesTo:["rosemonBurstMode"], method:"-" },
  mirageGaogamon: { name:"MirageGaogamon", stage:"Mega", evolvesTo:["shineGreymonBM"], method:"-" },
  uiForceVeedramon: { name:"UlforceVeedramon", stage:"Mega", evolvesTo:["gallantmonCM"], method:"-" },
  venomMyotismon: { name:"VenomMyotismon", stage:"Mega", evolvesTo:["omegamonZwartD"], method:"-" },
  lilithmon: { name:"Lilithmon", stage:"Mega", evolvesTo:["belphemonRM"], method:"-" },
  justimon: { name:"Justimon", stage:"Mega", evolvesTo:["omegamonZwartD"], method:"-" },
  piedmon: { name:"Piedmon", stage:"Mega", evolvesTo:["boltboutamon", "armageddemon"], method:"-" },
  lucemonSm: { name:"Lucemon SM", stage:"Mega", evolvesTo:["belphemonRM"], method:"-" },
  rustTyrannomon: { name:"RustTyranomon", stage:"Mega", evolvesTo:["omegamonZwartD"], method:"-" },
  samudramon: { name:"Samudramon", stage:"Mega", evolvesTo:["omegamonAlterB"], method:"-" },
  machinedramon: { name:"Machinedramon", stage:"Mega", evolvesTo:["armageddemon"], method:"-" },
  beelzemon: { name:"Beelzemon", stage:"Mega", evolvesTo:[], method:"-" },
  banchoLeomon: { name:"BanchoLeomon", stage:"Mega", evolvesTo:["chaosmon"], method:"-" },
  leviamon: { name:"Leviamon", stage:"Mega", evolvesTo:[], method:"-" },
  crusadermon: { name:"Crusadermon", stage:"Mega", evolvesTo:[], method:"-" },
  boltmon: { name:"Boltmon", stage:"Mega", evolvesTo:["omegamonZwartD"], method:"-" },
  creepymon: { name:"Creepymon", stage:"Mega", evolvesTo:["belphemonRM"], method:"-" },
  metalSeadramon: { name:"MetalSeadramon", stage:"Mega", evolvesTo:["armageddemon"], method:"-" },
  granKuwagamon: { name:"GranKuwagamon", stage:"Mega", evolvesTo:["omegamonZwartD"], method:"-" },
  belphemonSm: { name:"Belphemon SM", stage:"Mega", evolvesTo:["belphemonRM"], method:"-" },
  barbamon: { name:"Barbamon", stage:"Mega", evolvesTo:["belphemonRM"], method:"-" },
  examon: { name:"Examon", stage:"Mega", evolvesTo:["gallantmonCM"], method:"-" },
  titamon: { name:"Titamon", stage:"Mega", evolvesTo:["omegamonAlterB"], method:"-" },
  gankoomon: { name:"Gankoomon", stage:"Mega", evolvesTo:[], method:"-" },
  kentaurosmon: { name:"Kentaurosmon", stage:"Mega", evolvesTo:["gallantmonCM"], method:"-" },
  craniamon: { name:"Craniamon", stage:"Mega", evolvesTo:[], method:"-" },
  blackWarGreymon: { name:"BlackWarGreymon", stage:"Mega", evolvesTo:["omegamonZwart"], method:"-" },
  metalGarurumonBlack: { name:"MetalGarurumon (Black)", stage:"Mega", evolvesTo:["omegamonZwart"], method:"-" },
  chaosGallantmon: { name:"ChaosGallantmon", stage:"Mega", evolvesTo:["gallantmonCM"], method:"-" },
  kuzuhamon: { name:"Kuzuhamon", stage:"Mega", evolvesTo:["omegamonAlterB"], method:"-" },
  diaboromon: { name:"Diaboromon", stage:"Mega", evolvesTo:["armageddemon"], method:"-" },
  metalEtemon: { name:"MetalEtemon", stage:"Mega", evolvesTo:["omegamonAlterB"], method:"-" },
  platinumNumemon: { name:"PlatinumNumemon", stage:"Mega", evolvesTo:["omegamonZwartD"], method:"-" },
  ophanimon: { name:"Ophanimon", stage:"Mega", evolvesTo:["rosemonBurstMode"], method:"-" },
  imperialdramonDm: { name:"Imperialdramon DM", stage:"Mega", evolvesTo:["imperialdramonPM", "imperialdramonFM"], method:"-" },
  leopardmon: { name:"Leopardmon", stage:"Mega", evolvesTo:[], method:"-" },
  dynasmon: { name:"Dynasmon", stage:"Mega", evolvesTo:["gallantmonCM"], method:"-" },
  jijimon: { name:"Jijimon", stage:"Mega", evolvesTo:["omegamonZwartD"], method:"-" },
  mastemon: { name:"Mastemon", stage:"Mega", evolvesTo:["rosemonBurstMode"], method:"-" },
  alphamon: { name:"Alphamon", stage:"Mega", evolvesTo:["gallantmonCM"], method:"-" },
  jesmon: { name:"Jesmon", stage:"Mega", evolvesTo:["gallantmonCM"], method:"-" },
  minervamon: { name:"Minervamon", stage:"Mega", evolvesTo:[], method:"-" },
  dianamon: { name:"Dianamon", stage:"Mega", evolvesTo:["rosemonBurstMode"], method:"-" },
  darkdramon: { name:"Darkdramon", stage:"Mega", evolvesTo:["chaosmon"], method:"-" },
  kaiserGreymon: { name:"KaiserGreymon", stage:"Mega", evolvesTo:["susanoomon"], method:"-" },
  magnaGarurumon: { name:"MagnaGarurumon", stage:"Mega", evolvesTo:["susanoomon"], method:"-" },
  arresterdramon: { name:"Arresterdramon", stage:"Mega", evolvesTo:["omegamonAlterB"], method:"-" },
  omniShoutmon: { name:"OmniShoutmon", stage:"Mega", evolvesTo:["omegamonAlterB"], method:"-" },
  omegamon: { name:"Omegamon", stage:"Mega DNA", evolvesTo:[], method:"-" },
  omegamonZwart: { name:"Omegamon Zwart", stage:"Mega DNA", evolvesTo:[], method:"-" },
  imperialdramonFM: { name:"Imperialdramon FM", stage:"Mega DNA", evolvesTo:[], method:"-" },
  imperialdramonPM: { name:"Imperialdramon PM", stage:"Mega DNA", evolvesTo:[], method:"-" },
  susanoomon: { name:"Susanoomon", stage:"Mega DNA", evolvesTo:[], method:"-" },
  belphemonRM: { name:"Belphemon RM", stage:"Mega DNA", evolvesTo:[], method:"-" },
  omegamonZwartD: { name:"Omegamon Zwart D", stage:"Mega DNA", evolvesTo:[], method:"-" },
  armageddemon: { name:"Armageddemon", stage:"Mega DNA", evolvesTo:[], method:"-" },
  omegamonAlterB: { name:"Omegamon Alter-B", stage:"Mega DNA", evolvesTo:[], method:"-" },
  gallantmonCM: { name:"Gallantmon CM", stage:"Mega DNA", evolvesTo:[], method:"-" },
  shineGreymonBM: { name:"ShineGreymon BM", stage:"Mega DNA", evolvesTo:[], method:"-" },
  rosemonBurstMode: { name:"Rosemon Burst Mode", stage:"Mega DNA", evolvesTo:[], method:"-" },
  chaosmon: { name:"Chaosmon", stage:"Mega DNA", evolvesTo:[], method:"-" },
  boltboutamon: { name:"Boltboutamon", stage:"Mega DNA", evolvesTo:[], method:"-" }
};
